//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HizmetRehberi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HizmetRehberiDB2 : DbContext
    {
        public HizmetRehberiDB2()
            : base("name=HizmetRehberiDB2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Firmalar> Firmalars { get; set; }
        public virtual DbSet<Resimler> Resimlers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
